<template><h1 id="http010-http的常见header头★" tabindex="-1"><a class="header-anchor" href="#http010-http的常见header头★" aria-hidden="true">#</a> http010-http的常见header头★</h1>
<p>请求头：</p>
<h2 id="accept-请求报头域-指定客户端可以接收的类型有哪些-浏览器可接收的数据格式" tabindex="-1"><a class="header-anchor" href="#accept-请求报头域-指定客户端可以接收的类型有哪些-浏览器可接收的数据格式" aria-hidden="true">#</a> accept 请求报头域，指定客户端可以接收的类型有哪些 （浏览器可接收的数据格式）</h2>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  Accept: application/json
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="accept-encoding-指定客户端可接收的内容编码-压缩算法-如gzip" tabindex="-1"><a class="header-anchor" href="#accept-encoding-指定客户端可接收的内容编码-压缩算法-如gzip" aria-hidden="true">#</a> accept-encoding：指定客户端可接收的内容编码（压缩算法，如gzip）</h2>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  Accept-Encoding: gzip, deflate, br
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="accept-language-指定客户端可接收的编码语言" tabindex="-1"><a class="header-anchor" href="#accept-language-指定客户端可接收的编码语言" aria-hidden="true">#</a> accept-language：指定客户端可接收的编码语言</h2>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>Accept-Language: zh-CN,zh;q=0.9
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="host-用户指定请求资源的主机和端口号" tabindex="-1"><a class="header-anchor" href="#host-用户指定请求资源的主机和端口号" aria-hidden="true">#</a> host:用户指定请求资源的主机和端口号</h2>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>Host: github.com
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="cookies-用于存储本地的数据" tabindex="-1"><a class="header-anchor" href="#cookies-用于存储本地的数据" aria-hidden="true">#</a> cookies：用于存储本地的数据</h2>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  Cookie: _ga=GA1.2.190650762241.1552965769; _octo=GH1.1.1615682995.1552965770; _device_id=a0dc424c4c83e5b30b7c60f0da2f122; experiment:homepage_signup_flow=eyJ2ZXJzaW9uIjoiMawSIsInJvbGxPdXRQbGFjZW1lbnQiOjUuMzc1OTMxMTMzODM2NDkyLCJzdWJncm91cCI6ImNvbnRyb2wiLCJjcmVhdGVkQXQiOiIyMDIwLTAzLTI2VDAyOjAwOjM5LjIxM1oiLCJ1cGRhdGVkQXQiOiIyMDIwLTAzLTI2VDAyOjAwOjM5LjIxM1oifQ==; user_session=2jzw0VGpePO54lxXRgqvVobiKbi0ol-YSEV8NfllaJyQ3bkF; __Host-user_session_same_siZwIy0BNFrm5Ra%2BQc1%2FY1P6gL5kjcsjn%2B%2BdO7DSqUsjuQlZ7jx4NuDR306Sg%3D%3D--VTJEcRvbJw6Lw7Al--VIhGCbS1CA6EifesiPerag%3D%3D
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="refer-用于标识这个请求是从哪个页面来的-如登录前是从主页来的-就显示主页的信息" tabindex="-1"><a class="header-anchor" href="#refer-用于标识这个请求是从哪个页面来的-如登录前是从主页来的-就显示主页的信息" aria-hidden="true">#</a> refer：用于标识这个请求是从哪个页面来的，如登录前是从主页来的，就显示主页的信息</h2>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>  Referer: https://github.com/qdleader/qdleader
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="user-agent-ua-用于识别用户的使用的客户端版本等信息-浏览器信息-★" tabindex="-1"><a class="header-anchor" href="#user-agent-ua-用于识别用户的使用的客户端版本等信息-浏览器信息-★" aria-hidden="true">#</a> user-agent（UA）:用于识别用户的使用的客户端版本等信息(浏览器信息)★</h2>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="content-type-发送数据的格式-如-application-json" tabindex="-1"><a class="header-anchor" href="#content-type-发送数据的格式-如-application-json" aria-hidden="true">#</a> content-type 发送数据的格式，如 application/json</h2>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>Content-Type: application/manifest+json; charset=utf-8
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="connection-keep-alive-一次tcp链接重复使用" tabindex="-1"><a class="header-anchor" href="#connection-keep-alive-一次tcp链接重复使用" aria-hidden="true">#</a> connection:keep-alive 一次TCP链接重复使用</h2>
</template>
