<template><div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>
	<span class="token operator">&lt;</span>Radio<span class="token punctuation">.</span>Group
    onChange<span class="token operator">=</span><span class="token punctuation">{</span><span class="token parameter">value</span> <span class="token operator">=></span> <span class="token function">handleSelectChange</span><span class="token punctuation">(</span>value<span class="token punctuation">,</span> <span class="token string">'mydata'</span><span class="token punctuation">)</span><span class="token punctuation">}</span>
    <span class="token operator">></span>
    <span class="token operator">&lt;</span>Radio value<span class="token operator">=</span><span class="token string">"a"</span><span class="token operator">></span>item <span class="token number">1</span><span class="token operator">&lt;</span><span class="token operator">/</span>Radio<span class="token operator">></span>
    <span class="token operator">&lt;</span>Radio value<span class="token operator">=</span><span class="token string">"b"</span><span class="token operator">></span>item <span class="token number">2</span><span class="token operator">&lt;</span><span class="token operator">/</span>Radio<span class="token operator">></span>
    <span class="token operator">&lt;</span>Radio value<span class="token operator">=</span><span class="token string">"c"</span><span class="token operator">></span>item <span class="token number">3</span><span class="token operator">&lt;</span><span class="token operator">/</span>Radio<span class="token operator">></span>
  <span class="token operator">&lt;</span><span class="token operator">/</span>Radio<span class="token punctuation">.</span>Group<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div></template>
