<template><div class="language-css ext-css line-numbers-mode"><pre v-pre class="language-css"><code>   <span class="token selector">h1</span> <span class="token punctuation">{</span>
            <span class="token property">width</span><span class="token punctuation">:</span> 150px<span class="token punctuation">;</span>
            <span class="token property">background-image</span><span class="token punctuation">:</span> <span class="token function">linear-gradient</span><span class="token punctuation">(</span>to right<span class="token punctuation">,</span> <span class="token function">rgb</span><span class="token punctuation">(</span>101<span class="token punctuation">,</span> 163<span class="token punctuation">,</span> 13<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token function">rgb</span><span class="token punctuation">(</span>253<span class="token punctuation">,</span> 224<span class="token punctuation">,</span> 71<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token function">rgb</span><span class="token punctuation">(</span>220<span class="token punctuation">,</span> 38<span class="token punctuation">,</span> 38<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token property">background-clip</span><span class="token punctuation">:</span> text<span class="token punctuation">;</span>
            <span class="token property">-webkit-background-clip</span><span class="token punctuation">:</span> text<span class="token punctuation">;</span>
            <span class="token property">color</span><span class="token punctuation">:</span> transparent<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>很好看 😄</p>
</template>
