<template><div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>		<span class="token literal-property property">xAxis</span><span class="token operator">:</span> <span class="token punctuation">{</span>
				<span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">"category"</span><span class="token punctuation">,</span>
				<span class="token literal-property property">boundaryGap</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
				<span class="token literal-property property">axisLabel</span><span class="token operator">:</span> <span class="token punctuation">{</span>
					<span class="token literal-property property">showMinLabel</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
					<span class="token literal-property property">formatter</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
						<span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">value</span><span class="token operator">:</span> string</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
							<span class="token keyword">const</span> isLast <span class="token operator">=</span> value <span class="token operator">===</span> timeArr<span class="token punctuation">[</span>timeArr<span class="token punctuation">.</span>length <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
							<span class="token keyword">const</span> label <span class="token operator">=</span> isLast <span class="token operator">?</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">{a|</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>value<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">}</span><span class="token template-punctuation string">`</span></span> <span class="token operator">:</span> value<span class="token punctuation">;</span>
							<span class="token keyword">return</span> label<span class="token punctuation">;</span>
						<span class="token punctuation">}</span><span class="token punctuation">;</span>
					<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
					<span class="token literal-property property">showMaxLabel</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
					<span class="token literal-property property">rich</span><span class="token operator">:</span> <span class="token punctuation">{</span>
						<span class="token literal-property property">a</span><span class="token operator">:</span> <span class="token punctuation">{</span>
							<span class="token literal-property property">width</span><span class="token operator">:</span> <span class="token number">150</span><span class="token punctuation">,</span>
							<span class="token literal-property property">align</span><span class="token operator">:</span> <span class="token string">"left"</span>
						<span class="token punctuation">}</span>
					<span class="token punctuation">}</span><span class="token punctuation">,</span>
					<span class="token literal-property property">interval</span><span class="token operator">:</span> <span class="token number">0</span>
				<span class="token punctuation">}</span><span class="token punctuation">,</span>
				<span class="token literal-property property">axisPointer</span><span class="token operator">:</span> <span class="token punctuation">{</span>
					<span class="token literal-property property">label</span><span class="token operator">:</span> <span class="token punctuation">{</span>
						<span class="token literal-property property">show</span><span class="token operator">:</span> <span class="token boolean">true</span>
					<span class="token punctuation">}</span><span class="token punctuation">,</span>
					<span class="token literal-property property">z</span><span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span>
					<span class="token literal-property property">lineStyle</span><span class="token operator">:</span> <span class="token punctuation">{</span>
						<span class="token literal-property property">color</span><span class="token operator">:</span> <span class="token string">"#FBAC5E"</span><span class="token punctuation">,</span>
						<span class="token literal-property property">width</span><span class="token operator">:</span> <span class="token number">2</span>
					<span class="token punctuation">}</span>
				<span class="token punctuation">}</span><span class="token punctuation">,</span>
				<span class="token literal-property property">data</span><span class="token operator">:</span> timeArr
			<span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br></div></div></template>
