<template><p>今天在做一个动态表单规则的需求, 但是赋值给rules规则值之后，初始化的时候或者更改rules，表单就会立即检验报红。</p>
<p>解决办法如下两种：（推荐使用第一种）</p>
<p>第一种：通过form组件属性配置解决（validate-on-rule-change=&quot;false&quot;）</p>
<p>该属性是 是否在 rules 属性改变后立即触发一次验证, 我们配置成false，就不会立即触发了</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>el<span class="token operator">-</span>form ref<span class="token operator">=</span><span class="token string">"ruleFormRef"</span> <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"formDom"</span> <span class="token operator">:</span>model<span class="token operator">=</span><span class="token string">"ruleForm"</span> <span class="token operator">:</span>rules<span class="token operator">=</span><span class="token string">"rules"</span> label<span class="token operator">-</span>width<span class="token operator">=</span><span class="token string">"180px"</span> <span class="token operator">:</span>validate<span class="token operator">-</span>on<span class="token operator">-</span>rule<span class="token operator">-</span>change<span class="token operator">=</span><span class="token string">"false"</span><span class="token operator">></span>
    <span class="token operator">&lt;</span>el<span class="token operator">-</span>form<span class="token operator">-</span>item label<span class="token operator">=</span><span class="token string">"起止日期"</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>el<span class="token operator">-</span>form<span class="token operator">-</span>item prop<span class="token operator">=</span><span class="token string">"date1"</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>el<span class="token operator">-</span>date<span class="token operator">-</span>picker v<span class="token operator">-</span>model<span class="token operator">=</span><span class="token string">"ruleForm.date1"</span> type<span class="token operator">=</span><span class="token string">"date"</span> placeholder<span class="token operator">=</span><span class="token string">"选择日期"</span> style<span class="token operator">=</span><span class="token string">"width: 100%;"</span> <span class="token operator">/</span><span class="token operator">></span>
        <span class="token operator">&lt;</span><span class="token operator">/</span>el<span class="token operator">-</span>form<span class="token operator">-</span>item<span class="token operator">></span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>el<span class="token operator">-</span>form<span class="token operator">-</span>item<span class="token operator">></span>
<span class="token operator">&lt;</span><span class="token operator">/</span>el<span class="token operator">-</span>form<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>第二种：通过js解决</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token literal-property property">rules</span><span class="token operator">:</span> any <span class="token operator">=</span> <span class="token function">ref</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">date1</span><span class="token operator">:</span> <span class="token punctuation">[</span>
    <span class="token punctuation">{</span> <span class="token literal-property property">required</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token literal-property property">message</span><span class="token operator">:</span> <span class="token string">"请选择开始日期"</span><span class="token punctuation">,</span> <span class="token literal-property property">trigger</span><span class="token operator">:</span> <span class="token string">"change"</span> <span class="token punctuation">}</span>
  <span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>

<span class="token keyword">const</span> ruleFormRef <span class="token operator">=</span> ref<span class="token operator">&lt;</span>FormInstance<span class="token operator">></span><span class="token punctuation">(</span><span class="token punctuation">)</span>

 <span class="token function">setTimeout</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    ruleFormRef<span class="token punctuation">.</span>value<span class="token operator">!</span><span class="token punctuation">.</span><span class="token function">clearValidate</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token number">0</span><span class="token punctuation">)</span>

</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div></template>
