<template><p>如果有一个代理，能上github，但是git bash里面老是不能push/pull上去，</p>
<p>设置针对github.com本身(如果你需要代理的仓库，都是github上面的，只要设置这个)的代理：</p>
<h2 id="只对github-com" tabindex="-1"><a class="header-anchor" href="#只对github-com" aria-hidden="true">#</a> 只对github.com</h2>
<h3 id="找到自己的代理的port的4个数字的端口就行-不一定是7890口的" tabindex="-1"><a class="header-anchor" href="#找到自己的代理的port的4个数字的端口就行-不一定是7890口的" aria-hidden="true">#</a> 找到自己的代理的port的4个数字的端口就行，不一定是7890口的</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>git config <span class="token operator">--</span>global http<span class="token punctuation">.</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>github<span class="token punctuation">.</span>com<span class="token punctuation">.</span>proxy http<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">127.0</span><span class="token number">.0</span><span class="token number">.1</span><span class="token operator">:</span><span class="token number">7890</span>
#上面是别人的，如果你的代理是http类型的，如下设置：
git config <span class="token operator">--</span>global https<span class="token punctuation">.</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>github<span class="token punctuation">.</span>com<span class="token punctuation">.</span>proxy https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span><span class="token number">127.0</span><span class="token number">.0</span><span class="token number">.1</span><span class="token operator">:</span><span class="token number">7890</span>

git config <span class="token operator">--</span>global http<span class="token punctuation">.</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>github<span class="token punctuation">.</span>com<span class="token punctuation">.</span>proxy <span class="token string">'http://127.0.0.1:代理的port'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h2 id="取消代理" tabindex="-1"><a class="header-anchor" href="#取消代理" aria-hidden="true">#</a> 取消代理</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>git config <span class="token operator">--</span>global <span class="token operator">--</span>unset http<span class="token punctuation">.</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>github<span class="token punctuation">.</span>com<span class="token punctuation">.</span>proxy
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>针对所有仓库(包含github.com之外的仓库的代理)</p>
<h3 id="找到自己的代理的port的4个数字的端口就行-不一定是1080口的" tabindex="-1"><a class="header-anchor" href="#找到自己的代理的port的4个数字的端口就行-不一定是1080口的" aria-hidden="true">#</a> 找到自己的代理的port的4个数字的端口就行，不一定是1080口的</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>git config <span class="token operator">--</span>global http<span class="token punctuation">.</span>proxy <span class="token string">'socks5://127.0.0.1:7890'</span>
git config <span class="token operator">--</span>global https<span class="token punctuation">.</span>proxy <span class="token string">'socks5://127.0.0.1:7890'</span>

<span class="token comment">// git config --global http.proxy socks5 127.0.0.1:7890</span>
<span class="token comment">// git config --global https.proxy socks5 127.0.0.1:7890</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p>##上面是别人的，如果你的代理是http类型的，如下设置：</p>
<h2 id="找到自己的代理的port的4个数字的端口就行-不一定是1080口的-1" tabindex="-1"><a class="header-anchor" href="#找到自己的代理的port的4个数字的端口就行-不一定是1080口的-1" aria-hidden="true">#</a> 找到自己的代理的port的4个数字的端口就行，不一定是1080口的</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>git config <span class="token operator">--</span>global http<span class="token punctuation">.</span>proxy <span class="token number">127.0</span><span class="token number">.0</span><span class="token number">.1</span><span class="token operator">:</span><span class="token number">7890</span>
git config <span class="token operator">--</span>global https<span class="token punctuation">.</span>proxy <span class="token number">127.0</span><span class="token number">.0</span><span class="token number">.1</span><span class="token operator">:</span><span class="token number">7890</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>配置http代理</p>
<h2 id="查看代理命令" tabindex="-1"><a class="header-anchor" href="#查看代理命令" aria-hidden="true">#</a> 查看代理命令</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>git config <span class="token operator">--</span>global <span class="token operator">--</span><span class="token keyword">get</span> http<span class="token punctuation">.</span>proxy
git config <span class="token operator">--</span>global <span class="token operator">--</span><span class="token keyword">get</span> https<span class="token punctuation">.</span>proxy
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="取消代理命令" tabindex="-1"><a class="header-anchor" href="#取消代理命令" aria-hidden="true">#</a> 取消代理命令</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>git config <span class="token operator">--</span>global <span class="token operator">--</span>unset http<span class="token punctuation">.</span>proxy
git config <span class="token operator">--</span>global <span class="token operator">--</span>unset https<span class="token punctuation">.</span>proxy
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div></template>
